CREATE TABLE IF NOT EXISTS SHOP (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    ADDRESS VARCHAR (100),
    URL VARCHAR (100),
    ACTIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS OPENING_HOURS(
     SHOP_ID INTEGER,
     DAY VARCHAR(10),
     MINUTES_FROM INTEGER,
     MINUTES_TO INTEGER,
     FOREIGN KEY(SHOP_ID) REFERENCES SHOP(ID)
);

CREATE INDEX OPENING_HOURS_IDX ON OPENING_HOURS(SHOP_ID, DAY, MINUTES_FROM, MINUTES_TO);